packages:
  - apps/*
  - examples/*
  - packages/*
  - tools/*

catalog:
  "@tailwindcss/vite": ^4.2.4
  "@types/node": ^24.12.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@types/ws": ^8.18.1
  "@vitejs/plugin-react": ^6.0.1
  "@wterm/dom": ^0.1.9
  "@wterm/react": ^0.1.9
  agent-browser: ^0.26.0
  node-pty: ^1.1.0
  playwright: ^1.59.1
  react: ^19.2.5
  react-dom: ^19.2.5
  tailwindcss: ^4.2.4
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  ws: ^8.20.0

catalogMode: prefer

onlyBuiltDependencies:
  - agent-browser
  - node-pty
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
